# Generated by Django 3.2 on 2022-08-18 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Febrero', 'Febrero'), ('Septiembre', 'Septiembre'), ('Marzo', 'Marzo'), ('Junio', 'Junio'), ('Agosto', 'Agosto'), ('Mayo', 'Mayo'), ('Diciembre', 'Diciembre'), ('Enero', 'Enero'), ('Abril', 'Abril'), ('Julio', 'Julio')], max_length=100)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagoRealizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villapp.mes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_casa', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villapp.usuario')),
            ],
        ),
    ]
