# Generated by Django 3.1.7 on 2021-04-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0027_auto_20210403_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudas',
            name='PagodeAbril',
        ),
        migrations.RemoveField(
            model_name='deudas',
            name='PagodeAgosto',
        ),
        migrations.RemoveField(
            model_name='deudas',
            name='PagodeDiciembre',
        ),
        migrations.RemoveField(
            model_name='deudas',
            name='PagodeEnero',
        ),
        migrations.RemoveField(
            model_name='deudas',
            name='PagodeFebrero',
        ),
        migrations.RemoveField(
            model_name='deudas',
            name='PagodeJulio',
        ),
        migrations.RemoveField(
            model_name='deudas',
            name='PagodeJunio',
        ),
        migrations.RemoveField(
            model_name='deudas',
            name='PagodeMarzo',
        ),
        migrations.RemoveField(
            model_name='deudas',
            name='PagodeMayo',
        ),
        migrations.RemoveField(
            model_name='deudas',
            name='PagodeNoviembre',
        ),
        migrations.RemoveField(
            model_name='deudas',
            name='PagodeOctubre',
        ),
        migrations.RemoveField(
            model_name='deudas',
            name='PagodeSeptiembre',
        ),
        migrations.RemoveField(
            model_name='deudas',
            name='pagototal',
        ),
        migrations.RemoveField(
            model_name='tasadelmes',
            name='PagoPromedio',
        ),
        migrations.AddField(
            model_name='deudas',
            name='deudadepago',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tasadelmes',
            name='Tabla',
            field=models.CharField(max_length=10),
        ),
    ]
