# Generated by Django 3.1.7 on 2021-04-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0028_auto_20210406_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
